using Microsoft.AspNetCore.Identity;using System.ComponentModel.DataAnnotations;
namespace OperationsRequests.Domain;
public static class Roles{public const string PlatformAdmin="PlatformAdmin",CountryOpsManager="CountryOpsManager",TerritoryManager="TerritoryManager",SiteManager="SiteManager",StaffMember="StaffMember";public static readonly string[] All=[PlatformAdmin,CountryOpsManager,TerritoryManager,SiteManager,StaffMember];}
public sealed class ApplicationUser:IdentityUser{[MaxLength(120)]public string DisplayName{get;set;}="";public bool IsActive{get;set;}=true;public int? CountryId{get;set;}public int? TerritoryId{get;set;}public int? SiteId{get;set;}public Country? Country{get;set;}public Territory? Territory{get;set;}public Site? Site{get;set;}}
public sealed class Platform{public int Id{get;set;}[MaxLength(120)]public string Name{get;set;}="";public ICollection<Country> Countries{get;set;}=[];}
public sealed class Country{public int Id{get;set;}public int PlatformId{get;set;}[MaxLength(120)]public string Name{get;set;}="";[MaxLength(8)]public string Code{get;set;}="";public Platform Platform{get;set;}=null!;public ICollection<Territory> Territories{get;set;}=[];}
public sealed class Territory{public int Id{get;set;}public int CountryId{get;set;}[MaxLength(120)]public string Name{get;set;}="";public Country Country{get;set;}=null!;public ICollection<Site> Sites{get;set;}=[];}
public sealed class Site{public int Id{get;set;}public int TerritoryId{get;set;}[MaxLength(120)]public string Name{get;set;}="";[MaxLength(30)]public string Code{get;set;}="";public Territory Territory{get;set;}=null!;}
public enum RequestType{Training,Equipment,Maintenance,Compliance,Exception}public enum RequestPriority{Low,Medium,High}public enum RequestStatus{Submitted,UnderReview,AdditionalInfoRequested,Escalated,Approved,Declined,Resolved}
public sealed class TrainingRequest{public int Id{get;set;}[MaxLength(30)]public string RequestNumber{get;set;}="";public RequestType Type{get;set;}public RequestPriority Priority{get;set;}[MaxLength(180)]public string Title{get;set;}="";[MaxLength(2000)]public string Description{get;set;}="";public int SiteId{get;set;}public string RequestedById{get;set;}="";public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public RequestStatus Status{get;set;}=RequestStatus.Submitted;[Timestamp]public byte[] RowVersion{get;set;}=[];public Site Site{get;set;}=null!;public ApplicationUser RequestedBy{get;set;}=null!;public ICollection<RequestDecision> Decisions{get;set;}=[];public ICollection<RequestMessage> Messages{get;set;}=[];public ICollection<AuditEvent> AuditEvents{get;set;}=[];}
public sealed class RequestDecision{public int Id{get;set;}public int TrainingRequestId{get;set;}public string DecidedById{get;set;}="";[MaxLength(40)]public string Action{get;set;}="";[MaxLength(1000)]public string Note{get;set;}="";public DateTimeOffset DecidedAt{get;set;}=DateTimeOffset.UtcNow;public TrainingRequest TrainingRequest{get;set;}=null!;}
public sealed class RequestMessage{public int Id{get;set;}public int TrainingRequestId{get;set;}public string AuthorId{get;set;}="";[MaxLength(2000)]public string Body{get;set;}="";public bool IsQuestion{get;set;}public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public TrainingRequest TrainingRequest{get;set;}=null!;}
public sealed class AuditEvent{public long Id{get;set;}public int? TrainingRequestId{get;set;}[MaxLength(80)]public string Action{get;set;}="";public string? ActorId{get;set;}[MaxLength(120)]public string ActorName{get;set;}="System";public RequestStatus? PreviousStatus{get;set;}public RequestStatus? NewStatus{get;set;}[MaxLength(2000)]public string? Note{get;set;}public DateTimeOffset OccurredAt{get;set;}=DateTimeOffset.UtcNow;public TrainingRequest? TrainingRequest{get;set;}}
